# Generated by Django 3.1.3 on 2020-11-30 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20201130_0722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Revieww',
        ),
    ]
